# YT-DLP Online Interface – Build System
# ----------------------------------------------------------------------
# This Makefile handles compilation of Java (Maven), Python (Nuitka),
# and packaging for desktop/web/GraalVM/Docker.
#
# Linux users: you MUST install upx-ucl to keep the Python binary below
# 100 MB. On Debian/Ubuntu:   sudo apt install upx-ucl
#
# Optional: skip FFmpeg bundling to reduce binary size even further
# (the executable will then rely on a system‑installed ffmpeg).
#
#   make build-python BUNDLE_FFMPEG=0
#
# All targets that depend on Python automatically respect this flag.
#
# Extra Maven profiles can be passed via MVN_EXTRA_PROFILES, e.g.:
#   make build-package MVN_EXTRA_PROFILES=,win-x86
#
# On Windows 32‑bit, pytubefix is downgraded to 8.7.0 to avoid
# nodejs-wheel-binaries dependency (not available for 32‑bit).
# ----------------------------------------------------------------------

SHELL := /bin/bash
MVN   := ./mvnw

# ----------------------------------------------------------------------
# Platform detection
# ----------------------------------------------------------------------
PLATFORM := $(shell uname -s 2>/dev/null || echo Windows)
ifeq ($(findstring MINGW,$(PLATFORM)),MINGW)
    OS_IS_WINDOWS := yes
else ifeq ($(findstring MSYS,$(PLATFORM)),MSYS)
    OS_IS_WINDOWS := yes
else ifeq ($(PLATFORM),Windows)
    OS_IS_WINDOWS := yes
else
    OS_IS_WINDOWS := no
endif

# Python command
PY := $(if $(filter yes,$(OS_IS_WINDOWS)),python,python3)

# Python architecture (32 or 64) – used to special-case Windows 32‑bit
PYTHON_ARCH := $(shell $(PY) -c "import struct; print(struct.calcsize('P')*8)")

# Virtualenv paths
ifeq ($(OS_IS_WINDOWS),yes)
    VENV := .venv
    VENV_ACTIVATE := $(VENV)/Scripts/activate
    PIP := $(VENV)/Scripts/pip
    PYTHON := $(VENV)/Scripts/python
    CHMOD := true # no need
else
    VENV := .venv
    VENV_ACTIVATE := $(VENV)/bin/activate
    PIP := $(VENV)/bin/pip
    PYTHON := $(VENV)/bin/python
    CHMOD := chmod +x
endif

JPACKAGE := $(shell command -v jpackage 2>/dev/null || true)
VERSION  := 2.0.0

# Additional Maven profiles (comma-separated, e.g. ,win-x86)
MVN_EXTRA_PROFILES ?=

# ----------------------------------------------------------------------
# Build output directories
# ----------------------------------------------------------------------
BUILD_DIR        := build
BUILD_WEB_DIR    := $(BUILD_DIR)/web
BUILD_PACKAGE_DIR:= $(BUILD_DIR)/package
BUILD_GRAAL_DIR  := $(BUILD_DIR)/graal
BUILD_PYTHON_DIR := $(BUILD_DIR)/python

DOCKER_DIR       := docker
DOCKER_PYTHON    := $(DOCKER_DIR)/ytdlp            # always "ytdlp" (Linux env)

# ----------------------------------------------------------------------
# Maven / Graal / Nuitka output paths
# ----------------------------------------------------------------------
# Standard Maven output JAR (name generated by spring-boot-maven-plugin)
TARGET_JAR := target/videodownloader-$(VERSION).jar

# Copies used to avoid profile contamination
TARGET_JAR_WEB     := target/videodownloader-$(VERSION)-web.jar
TARGET_JAR_DESKTOP := target/videodownloader-$(VERSION)-desktop.jar

TARGET_NATIVE      := target/videodownloader
TARGET_JPACKAGE_DIR:= target/jpackage
TARGET_PYTHON_DIR  := target/python_build

# Python executable name (with .exe on Windows)
ifeq ($(OS_IS_WINDOWS),yes)
    PYTHON_EXEC := ytdlp.exe
else
    PYTHON_EXEC := ytdlp
endif

TARGET_PYTHON_EXEC := $(TARGET_PYTHON_DIR)/$(PYTHON_EXEC)

# ----------------------------------------------------------------------
# Final artifacts (placed in BUILD_DIR subfolders)
# ----------------------------------------------------------------------
BUILD_JAR     := $(BUILD_WEB_DIR)/videodownloader-$(VERSION).jar
BUILD_PACKAGE := $(BUILD_PACKAGE_DIR)/videodownloader-jpackage
BUILD_GRAAL   := $(BUILD_GRAAL_DIR)/videodownloader-graal
BUILD_PYTHON  := $(BUILD_PYTHON_DIR)/$(PYTHON_EXEC)

# ----------------------------------------------------------------------
# JPackage flags
# ----------------------------------------------------------------------
JPACKAGE_TARGET_FLAG := $(if $(JP_TARGET),--target-platform $(JP_TARGET),)

# ----------------------------------------------------------------------
# UPX compression flag (auto-detect)
# ----------------------------------------------------------------------
UPX_AVAILABLE := $(shell command -v upx 2>/dev/null)
NUIKTA_UPX := $(if $(UPX_AVAILABLE),--enable-plugin=upx,)

# Nuitka Windows-specific flags (use pefile instead of DependencyWalker)
NUIKTA_WINDOWS_FLAGS := $(if $(filter yes,$(OS_IS_WINDOWS)),--windows-dependency-tool=pefile,)

# ----------------------------------------------------------------------
# Nuitka output extension (.exe on Windows, .bin elsewhere)
# ----------------------------------------------------------------------
ifeq ($(OS_IS_WINDOWS),yes)
    NUIKTA_OUT_EXT := .exe
else
    NUIKTA_OUT_EXT := .bin
endif

# ----------------------------------------------------------------------
# FFmpeg bundling control (1 = include ffmpeg binary, 0 = skip)
# ----------------------------------------------------------------------
BUNDLE_FFMPEG ?= 1

# ----------------------------------------------------------------------
# FFmpeg bundling – detect OS and architecture (used when BUNDLE_FFMPEG=1)
# ----------------------------------------------------------------------
UNAME_S       := $(shell uname -s)
FFMPEG_BIN_DIR:= $(TARGET_PYTHON_DIR)/bin

ifeq ($(UNAME_S),Linux)
    FFMPEG_ARCH := x86_64
    FFMPEG_OS   := linux
else ifeq ($(UNAME_S),Darwin)
    FFMPEG_ARCH := x86_64
    FFMPEG_OS   := macos
else ifneq (,$(findstring MINGW,$(UNAME_S)))
    FFMPEG_ARCH := $(shell $(PY) -c "import struct; print('x86' if struct.calcsize('P')*8 == 32 else 'x86_64')")
    FFMPEG_OS   := windows
else ifneq (,$(findstring MSYS,$(UNAME_S)))
    FFMPEG_ARCH := $(shell $(PY) -c "import struct; print('x86' if struct.calcsize('P')*8 == 32 else 'x86_64')")
    FFMPEG_OS   := windows
else
    FFMPEG_ARCH := x86_64
    FFMPEG_OS   := linux
endif

# ----------------------------------------------------------------------
# Default target
# ----------------------------------------------------------------------
.DEFAULT_GOAL := help

# ======================================================================
# Phony targets
# ======================================================================
.PHONY: help clean test java-test python-test \
        build build-web build-web-graal build-package build-graal \
        update-docker update-docker-no-graal all \
        python-deps ffmpeg-download build-python

# ----------------------------------------------------------------------
help:
	@printf "YT-DLP Online Interface Build System\n\n"
	@printf "Usage: make <target> [OPTIONS]\n\n"
	@printf "Targets:\n"
	@printf "  help                   Show this message\n"
	@printf "  test                   Run all unit tests\n"
	@printf "  build                  Build Maven JAR (web profile)\n"
	@printf "  build-web              Build web app (JAR + Python)\n"
	@printf "  build-web-graal        Build web app with GraalVM native image\n"
	@printf "  build-package          Build desktop app with jPackage\n"
	@printf "  build-graal            Build desktop app with GraalVM native image\n"
	@printf "  build-python           Build standalone Python executable\n"
	@printf "  update-docker          Update docker/ folder with all artifacts\n"
	@printf "  update-docker-no-graal Update docker/ folder with JAR only\n"
	@printf "  clean                  Remove all build artifacts\n\n"
	@printf "Output structure:\n"
	@printf "  build/web/             - Web app JAR\n"
	@printf "  build/package/         - jPackage executables\n"
	@printf "  build/graal/           - GraalVM native binaries\n"
	@printf "  build/python/          - Nuitka Python executable\n\n"
	@printf "Environment variables:\n"
	@printf "  BUNDLE_FFMPEG=0        Build Python without embedded ffmpeg\n"
	@printf "                           (smaller binary, requires system ffmpeg)\n"
	@printf "  MVN_EXTRA_PROFILES=,win-x86  Add extra Maven profiles (comma-separated)\n\n"
	@printf "Prerequisites for Linux:\n"
	@printf "  sudo apt install upx-ucl   (required to keep binary < 100 MB)\n"
	@printf "Note for Windows 32‑bit:\n"
	@printf "  pytubefix is pinned to 8.7.0 automatically.\n"

# ----------------------------------------------------------------------
clean:
	rm -rf target $(VENV) .pytest_cache $(BUILD_DIR) $(DOCKER_DIR)

# ======================================================================
# Python environment
# ======================================================================
$(VENV_ACTIVATE):
	$(PY) -m venv $(VENV)
	$(PYTHON) -m pip install --upgrade pip

python-deps: $(VENV_ACTIVATE)
ifeq ($(OS_IS_WINDOWS)x$(PYTHON_ARCH),yesx32)
	@cp requirements.txt requirements_win32.txt
	@sed -i 's/^pytubefix.*/pytubefix==8.7.0/' requirements_win32.txt
	$(PIP) install -r requirements_win32.txt
	@rm -f requirements_win32.txt
else
	$(PIP) install -r requirements.txt
endif

ffmpeg-download:
	@mkdir -p $(FFMPEG_BIN_DIR)
	$(PY) scripts/download_ffmpeg.py $(FFMPEG_BIN_DIR) $(FFMPEG_ARCH)

# ----------------------------------------------------------------------
# Build the single‑file Python executable with Nuitka + optional FFmpeg
# ----------------------------------------------------------------------
$(TARGET_PYTHON_EXEC): python-deps $(if $(filter 1,$(BUNDLE_FFMPEG)),ffmpeg-download)
	@mkdir -p $(TARGET_PYTHON_DIR)
	$(PYTHON) -m compileall src/main/python
	$(PYTHON) -m nuitka \
		--onefile \
		$(NUIKTA_UPX) \
		$(NUIKTA_WINDOWS_FLAGS) \
		--assume-yes-for-downloads \
		--noinclude-unittest-mode=nofollow \
		--noinclude-pytest-mode=nofollow \
		--noinclude-setuptools-mode=nofollow \
		--include-package=ytdlp \
		--include-package=pydub \
		--include-package=pytubefix \
		$(if $(filter 1,$(BUNDLE_FFMPEG)),--include-data-dir=$(FFMPEG_BIN_DIR)=bin) \
		--output-dir=$(TARGET_PYTHON_DIR) \
		src/main/python/ytdlp/ytdlp.py
	@mv $(TARGET_PYTHON_DIR)/ytdlp$(NUIKTA_OUT_EXT) $@
	@echo "Python executable built: $@"
	@ls -lh $@

# ----------------------------------------------------------------------
# Centralised copy of the Python executable into the build tree
# ----------------------------------------------------------------------
$(BUILD_PYTHON): $(TARGET_PYTHON_EXEC) | $(BUILD_PYTHON_DIR)
	cp $< $@
	$(CHMOD) $@

$(BUILD_PYTHON_DIR):
	mkdir -p $@

build-python: $(BUILD_PYTHON)

# ======================================================================
# Maven JARs – separate targets to avoid profile contamination
# ======================================================================
$(TARGET_JAR_WEB):
	$(MVN) -Pweb-app -DskipTests clean package
	@cp $(TARGET_JAR) $@

$(TARGET_JAR_DESKTOP):
	$(MVN) -Pdesktop-package$(MVN_EXTRA_PROFILES) -DskipTests clean package
	@cp $(TARGET_JAR) $@

# Convenience target (builds the web JAR)
build: $(TARGET_JAR_WEB)

# ======================================================================
# Web build – JAR + Python in build/web
# ======================================================================
$(BUILD_WEB_DIR):
	mkdir -p $@

$(BUILD_JAR): $(TARGET_JAR_WEB) | $(BUILD_WEB_DIR)
	cp $< $@

build-web: $(BUILD_JAR) $(BUILD_PYTHON)
	@echo "Web build complete: $(BUILD_JAR)"

# ----------------------------------------------------------------------
# Web build with GraalVM native image
# ----------------------------------------------------------------------
$(BUILD_WEB_DIR)/videodownloader: $(TARGET_JAR_WEB) | $(BUILD_WEB_DIR)
	$(MVN) -Pweb-app -DskipTests native:compile
	cp target/videodownloader $@
	$(CHMOD) $@

build-web-graal: $(BUILD_WEB_DIR)/videodownloader $(BUILD_PYTHON)
	@echo "Web GraalVM build complete: $(BUILD_WEB_DIR)/videodownloader"

# ======================================================================
# Desktop – jPackage build (now uses the dedicated desktop JAR)
# ======================================================================
$(BUILD_PACKAGE_DIR):
	mkdir -p $@

$(BUILD_PACKAGE): $(TARGET_JAR_DESKTOP) $(BUILD_PYTHON) | $(BUILD_PACKAGE_DIR)
	@if [ -z "$(JPACKAGE)" ]; then \
		echo "jpackage not found in PATH. Install a JDK that includes jpackage."; exit 1; \
	fi
	rm -rf $(TARGET_JPACKAGE_DIR)
	mkdir -p target/jpackage-input
	cp $(TARGET_JAR_DESKTOP) target/jpackage-input/
	$(JPACKAGE) --type app-image \
		--name videodownloader \
		--input target/jpackage-input \
		--main-jar videodownloader-$(VERSION)-desktop.jar \
		--main-class com.ytdlp.videodownloader.DesktopLauncher \
		$(JPACKAGE_TARGET_FLAG) \
		--dest $(TARGET_JPACKAGE_DIR)
	@if [ -f "$(TARGET_JPACKAGE_DIR)/videodownloader/bin/videodownloader.exe" ]; then \
		cp $(TARGET_JPACKAGE_DIR)/videodownloader/bin/videodownloader.exe $@; \
	else \
		cp $(TARGET_JPACKAGE_DIR)/videodownloader/bin/videodownloader $@; \
	fi
	$(CHMOD) $@
	rm -rf target/jpackage-input
	@echo "Package build complete: $(BUILD_PACKAGE)"

build-package: $(BUILD_PACKAGE)

# ======================================================================
# Desktop – GraalVM native image
# ======================================================================
$(TARGET_NATIVE):
	$(MVN) -Pdesktop-graal -DskipTests native:compile

$(BUILD_GRAAL_DIR):
	mkdir -p $@

$(BUILD_GRAAL): $(TARGET_NATIVE) $(BUILD_PYTHON) | $(BUILD_GRAAL_DIR)
	cp $(TARGET_NATIVE) $@
	$(CHMOD) $@

build-graal: $(BUILD_GRAAL)
	@echo "GraalVM desktop build complete: $(BUILD_GRAAL)"

# ======================================================================
# Docker folder preparation
# ======================================================================
$(DOCKER_DIR):
	mkdir -p $@

update-docker: build-web build-web-graal $(DOCKER_DIR)
	cp $(BUILD_JAR)                     $(DOCKER_DIR)/videodownloader.jar
	cp $(BUILD_WEB_DIR)/videodownloader $(DOCKER_DIR)/videodownloader
	cp $(BUILD_PYTHON)                  $(DOCKER_PYTHON)
	$(CHMOD) $(DOCKER_DIR)/videodownloader
	$(CHMOD) $(DOCKER_PYTHON)
	@echo "Docker artifacts updated"

update-docker-no-graal: build-web $(DOCKER_DIR)
	cp $(BUILD_JAR)    $(DOCKER_DIR)/videodownloader.jar
	cp $(BUILD_PYTHON) $(DOCKER_PYTHON)
	$(CHMOD) $(DOCKER_PYTHON)
	@echo "Docker artifacts (JAR only) updated"

# ======================================================================
# Tests
# ======================================================================
python-test: python-deps
	$(PYTHON) -m unittest discover -s tests/python -p "test_*.py"

java-test:
	$(MVN) -Pweb-app test

test: java-test python-test

# ======================================================================
# Full pipeline
# ======================================================================
all: test build-web build-package build-graal